package services

import (
	"context"

	"github.com/google/go-github/github"
	"golang.org/x/oauth2"
)

func CreateGithubRepo(accessToken string, repoName string) (*github.Repository, error) {
	ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: accessToken},
	)
	tc := oauth2.NewClient(ctx, ts)
	client := github.NewClient(tc)

	repo := &github.Repository{
		Name:        github.String(repoName),
		Description: github.String("Generated by Packlify"),
		Homepage:    github.String("https://packlify.com"),
		Private:     github.Bool(false),
	}

	newRepo, _, err := client.Repositories.Create(ctx, "", repo)
	
	if err != nil {
		return nil, err
	}

	return newRepo, nil
}
